### ISSUE TITLE
Adding Date and Datetime inputs

### ISSUE THREAD

**Issue by charleystran** [westonganger/form_builder.cr#1]
I was wondering why there is no support for any kid of date or datetime input. In the end, most people will use an input text and have a JS picker on top, but from prototyping it would be useful. I was thinking that they could be how rails handles it with multiple select boxes for day, month, year.

**Comment by westonganger** [comment]
I have always used JS plugin for date or time, this is for good reason, they are quite complicated inputs. 

I do not include date or time inputs for the following other reasons:
- Neither of these inputs have been completely standardized
- None of the UI frameworks support either of these inputs
- When using JS plugins typically expect these inputs to be type="text"

The `date` input appears to be slightly useful however it has the following critical problems:

- Safari and Internet Explorer both do not support this input, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility
- UI for selecting the date / time is non-standard among browsers
- When using JS plugins typically expect these inputs to be type="text"

The `datetime` input appears to be deprecated and is fully non-standard: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/datetime

**Comment by westonganger** [comment]
That being said I have some slight interest in the `date` input. Once widespread compatibility and support is more complete it could be a nice feature to have.

**Comment by westonganger** [comment]
Been a few years looks like the situation has changed. Would be good to support these input types, probably we can just remove the validation on field type to be most dynamic.

**Comment by westonganger** [comment]
Relaxed the type validations now, will be released in the next version.
