### ISSUE TITLE
URL / email inputs

### ISSUE THREAD

**Issue by Uzay-G** [westonganger/form_builder.cr#2]
Do you think it would be worthwhile to add email / URL inputs? I would be willing to do it and open a PR for it if you agree.

They both just validate the form of the input on the frontend, but are useful for communicating intent.

**Comment by Uzay-G** [comment]
`submit` type would be quite useful too.

**Comment by westonganger** [comment]
No I am not interested in adding non-standard input types with specific frontend behaviour. I believe those kinds of things to be application specific concerns and are non-generic.
